### ISSUE TITLE
The images in markdown is not uploaded, could you upload the images to the same repo?

### ISSUE THREAD

**Issue by yanglr** [Guo749/lc_md#1]
@Guo749 Hi Guoguo, all the images in the markdown files is not uploaded, could you upload the images to the same repo?
I think it will help us understand the code you put in the repo. Thanks~

For example, the image file of the image link <https://github.com/Guo749/lc_md/blob/main/001-100.assets/image-20201228160053536.png> is not existed in this github repo.

**Comment by Guo749** [comment]
Thank you for your advice! It is very helpful!

I will upload them tonight

Regards,
Wenchao

Bravo Yeung ***@***.***> 于2021年9月1日周三 下午12:19写道：

**Comment by Guo749** [comment]
I just was notified by github of the limits one upload can be, like 100
pics a time at most

But most of my files contain more than that. So I will upload the PDF
instead and update it alternatively

Thank you for your advice!

Bravo Yeung ***@***.***> 于2021年9月1日周三 下午12:19写道：

**Comment by yanglr** [comment]
@Guo749 That's great, thanks~
